# frozen_string_literal: true

source "https://rubygems.org"

gem "rack-session", "~> 0.3.0"
gem "rackup", "~> 0.2.2"
gem "sidekiq", "~> 7.0"

gem "rspec-performance", "~> 0.1.0", require: false
gem "standard", "~> 1.16", require: false
